# Generated by Django 4.0.6 on 2022-09-19 20:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('House', 'House'), ('Utensils', 'Utensils'), ('Automobiles', 'Automobiles'), ('Clothes', 'Clothes'), ('Accessories', 'Accessories'), ('Electronics', 'Electronics'), ('Home appliances', 'Home appliances'), ('Computers', 'Computers'), ('Videogames', 'Videogames'), ('Others', 'Others')], default='Casa', max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.IntegerField()),
                ('image_url', models.URLField(blank=True)),
                ('contact', models.CharField(max_length=11)),
                ('email', models.EmailField(max_length=200)),
            ],
        ),
    ]
