# Generated by Django 4.0.6 on 2022-09-20 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('House', 'House'), ('Utensils', 'Utensils'), ('Automobiles', 'Automobiles'), ('Clothes', 'Clothes'), ('Accessories', 'Accessories'), ('Electronics', 'Electronics'), ('Home appliances', 'Home appliances'), ('Computers', 'Computers'), ('Videogames', 'Videogames'), ('Others', 'Others')], default='House', max_length=200),
        ),
    ]
